theme: jekyll-theme-minimal
title: Modern
description: A website about the relationship between technology and the movie industry
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
  - title: Test
    url: test
