theme: jekyll-theme-minimal
title: Modern Times: Rise of Technology in Cinema
description: A website about the relationship between technology and the movie industry
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
